version: '3.5'

networks:
  backend:
    driver: bridge

services:
  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: "rabbitmq"
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    restart: always
